services:
   db:
      image: postgres:13
      container_name: my-postgres
      environment:
         POSTGRES_DB: nutelladb
         POSTGRES_PASSWORD: mysecretpassword
      ports:
         - '5432:5432'
      volumes:
         - postgres_data:/var/lib/postgresql/data

volumes:
   postgres_data:
