import type { Metadata } from 'next';
import './globals.css';
import { Figtree } from 'next/font/google';
import {
	ClerkProvider,
	SignInButton,
	SignedIn,
	SignedOut,
	UserButton,
} from '@clerk/nextjs';
import { ThemeProvider } from '@/components/theme-provider';

const figtree = Figtree({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Nukela',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang='en' suppressHydrationWarning>
				<body className={`${figtree.className} antialiased`}>
					<ThemeProvider
						attribute='class'
						defaultTheme='system'
						enableSystem
						disableTransitionOnChange
					>
						{children}
					</ThemeProvider>
				</body>
			</html>
		</ClerkProvider>
	);
}
